/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SimpleClass */

#ifndef _Included_SimpleClass
#define _Included_SimpleClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SimpleClass
 * Method:    getIntVal
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_SimpleClass_getIntVal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     SimpleClass
 * Method:    setIntVal
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_SimpleClass_setIntVal
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     SimpleClass
 * Method:    initNativeSimpleClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_SimpleClass_initNativeSimpleClass
  (JNIEnv *, jobject);

/*
 * Class:     SimpleClass
 * Method:    destroyNativeSimpleClass
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SimpleClass_destroyNativeSimpleClass
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
